// Docs: https://www.instantdb.com/docs/modeling-data

import { i } from "@instantdb/react";

const _schema = i.schema({
  entities: {
    $files: i.entity({
      path: i.string().unique().indexed(),
      url: i.string(),
    }),
    $streams: i.entity({
      abortReason: i.string().optional(),
      clientId: i.string().unique().indexed(),
      done: i.boolean().optional(),
      size: i.number().optional(),
    }),
    $users: i.entity({
      email: i.string().unique().indexed().optional(),
      imageURL: i.string().optional(),
      name: i.string().optional(),
      timeZone: i.string().optional(),
    }),

    // Client-visible metadata for a connected Google identity. Provider tokens
    // live in googleCredentials, which is denied to clients in instant.perms.ts.
    googleAccounts: i.entity({
      ownerId: i.string().indexed(),
      providerAccountId: i.string().unique().indexed(),
      email: i.string().indexed(),
      displayName: i.string().optional(),
      imageURL: i.string().optional(),
      scopes: i.json().optional(),
      connectedAt: i.date(),
      updatedAt: i.date(),
      lastErrorCode: i.string().optional(),
    }),
    googleCredentials: i.entity({
      encryptedRefreshToken: i.string(),
      encryptionKeyVersion: i.number(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    calendars: i.entity({
      ownerId: i.string().indexed(),
      providerKey: i.string().unique().indexed(),
      googleCalendarId: i.string().indexed(),
      summary: i.string(),
      description: i.string().optional(),
      timeZone: i.string().optional(),
      colorId: i.string().optional(),
      backgroundColor: i.string().optional(),
      foregroundColor: i.string().optional(),
      accessRole: i.string().indexed(),
      isPrimary: i.boolean(),
      isDeleted: i.boolean(),
      defaultReminders: i.json().optional(),
      notificationSettings: i.json().optional(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    calendarPreferences: i.entity({
      ownerId: i.string().indexed(),
      visible: i.boolean(),
      isDefault: i.boolean(),
      colorOverride: i.string().optional(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    calendarEvents: i.entity({
      ownerId: i.string().indexed(),
      providerKey: i.string().unique().indexed(),
      googleEventId: i.string().indexed(),
      iCalUID: i.string().indexed().optional(),
      etag: i.string().optional(),
      sequence: i.number(),
      status: i.string().indexed(),
      eventType: i.string().indexed(),
      summary: i.string().optional(),
      description: i.string().optional(),
      location: i.string().optional(),
      colorId: i.string().optional(),
      visibility: i.string().optional(),
      transparency: i.string().optional(),
      htmlLink: i.string().optional(),
      isAllDay: i.boolean(),
      startAt: i.date().indexed().optional(),
      endAt: i.date().indexed().optional(),
      startDate: i.string().indexed().optional(),
      endDate: i.string().indexed().optional(),
      startTimeZone: i.string().optional(),
      endTimeZone: i.string().optional(),
      recurrence: i.json().optional(),
      recurringEventId: i.string().indexed().optional(),
      originalStartAt: i.date().optional(),
      originalStartDate: i.string().optional(),
      attendees: i.json().optional(),
      organizer: i.json().optional(),
      creator: i.json().optional(),
      reminders: i.json().optional(),
      conferenceData: i.json().optional(),
      attachments: i.json().optional(),
      guestsCanInviteOthers: i.boolean().optional(),
      guestsCanModify: i.boolean().optional(),
      guestsCanSeeOtherGuests: i.boolean().optional(),
      anyoneCanAddSelf: i.boolean().optional(),
      privateCopy: i.boolean().optional(),
      locked: i.boolean().optional(),
      providerCreatedAt: i.date().optional(),
      providerUpdatedAt: i.date().indexed(),
      syncedAt: i.date().indexed(),
    }),
    todoLists: i.entity({
      ownerId: i.string().indexed(),
      name: i.string(),
      color: i.string(),
      icon: i.string().optional(),
      isSystem: i.boolean(),
      order: i.number().indexed(),
      archivedAt: i.date().optional(),
      createdAt: i.string(),
      updatedAt: i.string(),
    }),
    todos: i.entity({
      ownerId: i.string().indexed(),
      title: i.string(),
      description: i.string().optional(),
      completed: i.boolean(),
      status: i.string().indexed().optional(),
      priority: i.string().indexed().optional(),
      durationMinutes: i.number().optional(),
      scheduledDate: i.string().optional(),
      dueAt: i.date().indexed().optional(),
      deadlineAt: i.date().indexed().optional(),
      timeZone: i.string().optional(),
      recurrence: i.json().optional(),
      recurrenceAnchor: i.date().optional(),
      completedAt: i.date().optional(),
      cancelledAt: i.date().optional(),
      schedulingStatus: i.string().indexed().optional(),
      isScheduleLocked: i.boolean().optional(),
      order: i.number().indexed(),
      createdAt: i.string(),
      updatedAt: i.string(),
    }),
    labels: i.entity({
      ownerId: i.string().indexed(),
      name: i.string(),
      color: i.string(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    taskCompletions: i.entity({
      ownerId: i.string().indexed(),
      occurrenceKey: i.string().unique().indexed(),
      occurrenceAt: i.date().indexed(),
      completedAt: i.date(),
      createdAt: i.date(),
    }),
  },
  links: {
    $streams$files: {
      forward: { on: "$streams", has: "many", label: "$files" },
      reverse: {
        on: "$files",
        has: "one",
        label: "$stream",
        onDelete: "cascade",
      },
    },
    $usersLinkedPrimaryUser: {
      forward: {
        on: "$users",
        has: "one",
        label: "linkedPrimaryUser",
        onDelete: "cascade",
      },
      reverse: {
        on: "$users",
        has: "many",
        label: "linkedGuestUsers",
      },
    },

    googleAccountOwner: {
      forward: {
        on: "googleAccounts",
        has: "one",
        label: "user",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "$users", has: "many", label: "googleAccounts" },
    },
    googleCredentialAccount: {
      forward: {
        on: "googleCredentials",
        has: "one",
        label: "googleAccount",
        required: true,
        onDelete: "cascade",
      },
      reverse: {
        on: "googleAccounts",
        has: "one",
        label: "credential",
      },
    },
    calendarAccount: {
      forward: {
        on: "calendars",
        has: "one",
        label: "googleAccount",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "googleAccounts", has: "many", label: "calendars" },
    },
    calendarOwner: {
      forward: {
        on: "calendars",
        has: "one",
        label: "user",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "$users", has: "many", label: "calendars" },
    },
    calendarPreferenceCalendar: {
      forward: {
        on: "calendarPreferences",
        has: "one",
        label: "calendar",
        required: true,
        onDelete: "cascade",
      },
      reverse: {
        on: "calendars",
        has: "many",
        label: "preferences",
      },
    },
    calendarPreferenceOwner: {
      forward: {
        on: "calendarPreferences",
        has: "one",
        label: "user",
        required: true,
        onDelete: "cascade",
      },
      reverse: {
        on: "$users",
        has: "many",
        label: "calendarPreferences",
      },
    },
    calendarEventCalendar: {
      forward: {
        on: "calendarEvents",
        has: "one",
        label: "calendar",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "calendars", has: "many", label: "events" },
    },
    calendarEventOwner: {
      forward: {
        on: "calendarEvents",
        has: "one",
        label: "user",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "$users", has: "many", label: "calendarEvents" },
    },
    todoTodoList: {
      forward: {
        on: "todos",
        has: "one",
        label: "todoList",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "todoLists", has: "many", label: "todos" },
    },
    todoOwner: {
      forward: {
        on: "todos",
        has: "one",
        label: "user",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "$users", has: "many", label: "todos" },
    },
    todoListOwner: {
      forward: {
        on: "todoLists",
        has: "one",
        label: "user",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "$users", has: "many", label: "todoLists" },
    },
    labelOwner: {
      forward: {
        on: "labels",
        has: "one",
        label: "user",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "$users", has: "many", label: "labels" },
    },
    todoLabels: {
      forward: { on: "todos", has: "many", label: "labels" },
      reverse: { on: "labels", has: "many", label: "todos" },
    },
    taskCompletionTodo: {
      forward: {
        on: "taskCompletions",
        has: "one",
        label: "todo",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "todos", has: "many", label: "completions" },
    },
    taskCompletionOwner: {
      forward: {
        on: "taskCompletions",
        has: "one",
        label: "user",
        required: true,
        onDelete: "cascade",
      },
      reverse: { on: "$users", has: "many", label: "taskCompletions" },
    },
  },
  rooms: {},
});

type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
